name: insuranceapp
description: A new Flutter project.

publish_to: "none"

#Version app
version: 1.0.7+16

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  after_layout: ^1.2.0
  another_flushbar: ^1.12.29
  bottom_navigation_bar: ^1.0.1
  bubble: ^1.2.1
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.2.0
  country_list_pick: ^1.0.1+6
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.0.0
  dropdown_search: ^5.0.3
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  firebase_core: ^2.3.0
  firebase_messaging: ^14.3.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.2
  flutter_flavor: ^3.1.1
  flutter_form_builder: ^9.0.0
  flutter_inappwebview: ^5.7.1
  flutter_local_notifications: ^14.1.0
  flutter_masked_text2: ^0.9.1
  fluttertoast: ^8.1.1
  form_builder_validators: ^9.0.0
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  get_it: ^7.2.0
  google_maps_flutter: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^0.8.6
  injectable: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  intl_phone_field: ^3.1.0
  json_annotation: ^4.7.0
  location: ^5.0.3
  logger: ^1.1.0
  modal_bottom_sheet:
    git:
      url: https://github.com/followthemoney1/modal_bottom_sheet.git
      ref: main
      path: modal_bottom_sheet
  overlay_support: ^2.0.1
  path_provider: ^2.0.11
  provider: ^6.0.4
  pubnub: ^4.2.2
  retrofit: ^4.0.1
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_barcodes: ^21.2.5
  timeago: ^3.3.0
  url_launcher: ^6.1.6
  adaptive_action_sheet: ^2.0.2
  country_pickers: ^2.0.0
  flutter_svg: ^2.0.0+1
  flutter_native_splash: ^2.2.16
  map_launcher: ^2.5.0+1
  lottie: ^2.3.0
  new_version: 
    git:
      url: https://github.com/t-toum/new_version.git
  package_info_plus: ^4.0.1
  permission_handler: ^10.2.0
  jwt_decoder: ^2.0.1
  flutter_automation: ^2.0.0
  # background_location: ^0.8.1
dev_dependencies:
  build_runner: ^2.3.2
  dependency_validator: ^3.2.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/flags/
    - assets/translations/
    - assets/lotties/
  fonts:
    - family: NotoSansLao
      fonts:
        - asset: assets/fonts/NotoSansLao/NotoSansLao-Black.ttf
        - asset: assets/fonts/NotoSansLao/NotoSansLao-Bold.ttf
        - asset: assets/fonts/NotoSansLao/NotoSansLao-ExtraBold.ttf
        - asset: assets/fonts/NotoSansLao/NotoSansLao-ExtraLight.ttf
        - asset: assets/fonts/NotoSansLao/NotoSansLao-Light.ttf
        - asset: assets/fonts/NotoSansLao/NotoSansLao-Medium.ttf
        - asset: assets/fonts/NotoSansLao/NotoSansLao-Regular.ttf
        - asset: assets/fonts/NotoSansLao/NotoSansLao-SemiBold.ttf
        - asset: assets/fonts/NotoSansLao/NotoSansLao-Thin.ttf
          style: normal
# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/logo-insurance.png"
